name: "Nox Tests"

on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron: "20 1 * * sat"

defaults:
    run:
        shell: bash

jobs:
    tests:
        name: "Testing on ${{ matrix.os }}"
        runs-on: "${{ matrix.os }}"

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    # TODO:
                    # - macos-latest
                    # - windows-latest

        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v4"

            - name: "Set up Python"
              uses: "actions/setup-python@v5"
              with:
                  python-version: "3.11"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install nox poetry

            - name: "Run nox"
              run: |
                  python -m nox -r

            - name: "Upload coverage data"
              uses: actions/upload-artifact@v3
              with:
                  name: covdata
                  path: .coverage.*
